name: Auto Merge Dependabot
on: pull_request

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Only do this when dependabot
      if: contains(github.ref, 'dependabot')
      run: echo "Hello ref ${{ github.ref }}"
    - name: automerge
      uses: developerayo/automerge-action@bot
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
